services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE"]
    volumes:
      - memgraph-data:/var/lib/memgraph

volumes:
  memgraph-data:
