services:
  memgraph:
    image: memgraph/memgraph-mage:3.8.0
    ports:
      - "7688:7687"
      - "7444:7444"
    command: ["--log-level=TRACE", "--bolt-server-name-for-init=Neo4j/5.2.0"]
    volumes:
      - memgraph-data:/var/lib/memgraph

volumes:
  memgraph-data:
