ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.bootstrap.StartupKt.configureStartup
      - com.example.bootstrap.HttpKt.configureHttp
      - com.example.bootstrap.SerializationKt.configureSerialization
      - com.example.bootstrap.StatusPagesKt.configureStatusPages
      - com.example.bootstrap.RoutingKt.configureRouting

